// test 5

let dados = [
    {
        titulo: "Ubuntu",
        descricao: "O Ubuntu é uma das distribuições Linux mais populares, especialmente entre iniciantes, devido à sua facilidade de uso e grande comunidade. Ele oferece suporte a longo prazo (LTS) e uma ampla gama de softwares disponíveis. Além disso, o Ubuntu é uma excelente escolha tanto para uso em desktop quanto em servidores. Com um foco em atualizações regulares e a introdução de novas tecnologias, o Ubuntu se destaca pela sua estabilidade e vasta documentação, o que facilita a vida de novos usuários. No entanto, alguns podem considerá-lo sobrecarregado com software desnecessário.",
        link: "https://ubuntu.com/",
        imagem: "distro_icons/128/128_ubuntu.png",
        dataLancamento: "2004",
        requisitos: "1 GB RAM, 10 GB de espaço em disco",
        foco: "desktop, servidor, desenvolvimento",
        gerenciadorPacotes: "apt",
        ambienteDesktopPadrao: "GNOME",
        pros: "Grande comunidade, ampla variedade de software, fácil de usar, suporte a longo prazo",
        contras: "Pode ser considerado bloatware por alguns usuários, atualizações podem ser intrusivas"
    },
    {
        titulo: "Fedora",
        descricao: "O Fedora é conhecido por seu foco em inovação e por sempre trazer as últimas tecnologias, sendo uma ótima escolha para desenvolvedores. Ele utiliza tecnologias como Wayland e Btrfs por padrão, e é um excelente ambiente para quem busca uma plataforma moderna e robusta. Sua comunidade é bastante ativa, e o Fedora tem uma postura firme em relação ao uso de software livre. No entanto, as atualizações frequentes podem ser um desafio para iniciantes, pois podem causar instabilidades ocasionais. Ainda assim, é uma excelente escolha para quem quer estar na vanguarda da tecnologia Linux.",
        link: "https://getfedora.org/",
        imagem: "distro_icons/128/128_fedora_newlogo.png",
        dataLancamento: "2003",
        requisitos: "2 GB RAM, 20 GB de espaço em disco",
        foco: "desktop, desenvolvimento, servidor",
        gerenciadorPacotes: "dnf",
        ambienteDesktopPadrao: "GNOME",
        pros: "Inovação constante, comunidade ativa, ótimo para desenvolvimento, estabilidade",
        contras: "Curva de aprendizado um pouco mais íngreme para iniciantes, atualizações frequentes podem causar instabilidades"
    },
    {
        titulo: "Debian",
        descricao: "O Debian é conhecido por ser uma das distribuições Linux mais estáveis e confiáveis, com uma história longa e respeitável. Ele é amplamente utilizado em servidores, mas também pode ser utilizado como sistema desktop. Famoso por sua filosofia de software livre, o Debian oferece uma base sólida para muitas outras distribuições, como o Ubuntu. Para iniciantes, a interface e a configuração inicial podem parecer um pouco mais difíceis, e as atualizações são menos frequentes em comparação com outras distribuições, focando mais em estabilidade do que em ter os pacotes mais recentes.",
        link: "https://www.debian.org/",
        imagem: "distro_icons/128/128_debian.png",
        dataLancamento: "1993",
        requisitos: "1 GB RAM, 10 GB de espaço em disco",
        foco: "servidor, desktop",
        gerenciadorPacotes: "apt",
        ambienteDesktopPadrao: "GNOME",
        pros: "Estabilidade, grande variedade de pacotes, comunidade ativa, base para muitas outras distros",
        contras: "Interface menos amigável para iniciantes, atualizações podem ser mais lentas"
    },
    {
        titulo: "Arch Linux",
        descricao: "O Arch Linux é uma distribuição projetada para usuários que querem ter controle total sobre seu sistema. É altamente personalizável, mas também exige que o usuário faça a instalação e configuração manualmente, o que pode ser intimidante para iniciantes. No entanto, para aqueles que têm paciência e desejo de aprender, o Arch oferece uma experiência poderosa, com a capacidade de criar um sistema operacional sob medida. Ele segue um modelo de atualização contínua (rolling release), garantindo que você sempre tenha as últimas versões de softwares. É uma excelente escolha para desenvolvedores e entusiastas de Linux.",
        link: "https://archlinux.org/",
        imagem: "distro_icons/128/128_arch.png",
        dataLancamento: "2002",
        requisitos: "128 MB RAM, 8 GB de espaço em disco",
        foco: "personalização, desenvolvimento",
        gerenciadorPacotes: "pacman",
        ambienteDesktopPadrao: "Xfce",
        pros: "Grande flexibilidade, comunidade ativa, sempre atualizado",
        contras: "Curva de aprendizado íngreme, instalação complexa"
    },
    {
        titulo: "Manjaro",
        descricao: "Baseado no Arch Linux, o Manjaro visa trazer os benefícios dessa poderosa distribuição para um público mais amplo, oferecendo uma instalação fácil e uma experiência mais amigável. Com o Manjaro, você obtém o melhor do Arch Linux, mas com ferramentas que facilitam a instalação e o gerenciamento de pacotes. Ele é ideal para usuários que querem a flexibilidade e personalização do Arch, mas sem o esforço envolvido na instalação manual. Manjaro também oferece várias edições com diferentes ambientes de desktop, permitindo que os usuários escolham a interface que mais se adequa ao seu estilo.",
        link: "https://manjaro.org/",
        imagem: "distro_icons/128/128_manjaro.png",
        dataLancamento: "2011",
        requisitos: "1 GB RAM, 20 GB de espaço em disco",
        foco: "desktop, iniciantes",
        gerenciadorPacotes: "pacman",
        ambienteDesktopPadrao: "XFCE",
        pros: "Fácil de instalar, baseado em Arch Linux, comunidade ativa",
        contras: "Menos personalizável que o Arch Linux puro"
    },
    {
        titulo: "Linux Mint",
        descricao: "O Linux Mint é uma das distribuições mais recomendadas para quem está migrando do Windows, graças ao seu ambiente de desktop intuitivo e familiar. Baseado no Ubuntu, ele herda sua estabilidade e grande variedade de softwares, mas com um foco maior em simplicidade e usabilidade. O Cinnamon, o ambiente desktop padrão, é moderno e elegante, tornando o Linux Mint uma excelente escolha para iniciantes que buscam uma experiência tranquila e sem complicações. Embora o Linux Mint seja altamente estável, ele pode ficar um pouco desatualizado em relação ao Ubuntu devido à sua política de atualizações mais conservadora.",
        link: "https://linuxmint.com/",
        imagem: "distro_icons/128/128_mint.png",
        dataLancamento: "2006",
        requisitos: "128 MB RAM, 10 GB de espaço em disco",
        foco: "desktop, iniciantes",
        gerenciadorPacotes: "apt",
        ambienteDesktopPadrao: "Cinnamon",
        pros: "Fácil de usar, interface elegante, grande variedade de ambientes de desktop",
        contras: "Pode se tornar um pouco desatualizado em relação ao Ubuntu"
    },
    {
        titulo: "OpenSUSE",
        descricao: "O OpenSUSE é uma distribuição que se destaca por suas ferramentas robustas de configuração e uma comunidade bastante ativa. Com o YaST, um dos gerenciadores de sistema mais completos do Linux, o OpenSUSE permite que os usuários configurem praticamente tudo com facilidade. Ele é altamente adequado para desenvolvedores e profissionais que procuram um ambiente de trabalho estável, mas também oferece flexibilidade para o uso em desktops. O OpenSUSE tem duas versões principais: Leap, para quem quer estabilidade, e Tumbleweed, para quem quer as últimas atualizações de software. No entanto, pode ser mais pesado que outras distribuições.",
        link: "https://opensuse.org/",
        imagem: "distro_icons/128/128_suse.png",
        dataLancamento: "2005",
        requisitos: "1 GB RAM, 20 GB de espaço em disco",
        foco: "desktop, servidor, desenvolvimento",
        gerenciadorPacotes: "zypper",
        ambienteDesktopPadrao: "KDE Plasma",
        pros: "Grande comunidade, YaST (ferramenta de configuração poderosa), suporte a longo prazo",
        contras: "Pode ser um pouco mais pesado que outras distribuições"
    },
    {
        titulo: "Kali Linux",
        descricao: "O Kali Linux é uma distribuição voltada para segurança cibernética, sendo amplamente utilizada por profissionais de segurança, hackers éticos e entusiastas de testes de penetração. Ele vem pré-instalado com uma grande variedade de ferramentas específicas para análise forense, engenharia reversa e testes de penetração, como o Metasploit, Nmap e Wireshark. Embora seja uma excelente ferramenta para profissionais da área, o Kali não é recomendado como sistema operacional principal para uso diário, pois não é otimizado para isso e pode ser instável para atividades comuns de desktop.",
        link: "https://www.kali.org/",
        imagem: "distro_icons/128/128_kali.png",
        dataLancamento: "2013",
        requisitos: "2 GB RAM, 20 GB de espaço em disco",
        foco: "segurança, hacking",
        gerenciadorPacotes: "apt",
        ambienteDesktopPadrao: "GNOME",
        pros: "Ampla variedade de ferramentas de segurança, comunidade ativa, documentação extensa",
        contras: "Não é recomendado para uso diário, pode ser instável para tarefas não relacionadas à segurança"
    },
    {
        titulo: "Pop!_OS",
        descricao: "Desenvolvido pela System76, o Pop!_OS é uma distribuição baseada no Ubuntu, com um foco especial em otimizar o desempenho e fornecer uma experiência de uso fluida em desktops e laptops. Ele é especialmente recomendado para quem possui hardware System76, pois oferece integração e suporte nativo para esses dispositivos. Com uma interface gráfica moderna e uma abordagem que valoriza a produtividade, o Pop!_OS também é muito popular entre desenvolvedores e criadores de conteúdo. Embora ofereça um ótimo desempenho, sua biblioteca de softwares pode ser um pouco mais limitada em comparação com outras distribuições mais populares.",
        link: "https://pop.system76.com/",
        imagem: "distro_icons/128/128_pop.png",
        dataLancamento: "2017",
        requisitos: "2 GB RAM, 20 GB de espaço em disco",
        foco: "desktop, desempenho",
        gerenciadorPacotes: "apt",
        ambienteDesktopPadrao: "GNOME",
        pros: "Desempenho otimizado, integração com hardware System76, interface elegante",
        contras: "Menor variedade de software em comparação com distribuições mais populares"
    },
    {
        titulo: "Solus",
        descricao: "O Solus é uma distribuição independente que se destaca por seu foco em uma experiência de usuário coesa e de alta qualidade. Com uma interface de usuário moderna e amigável, o Solus oferece um ambiente desktop completo e otimizado. É conhecido por sua abordagem simples e eficaz, além de um ciclo de lançamento de atualizações contínuas. O Solus é ideal para quem busca uma distribuição fácil de usar e bem integrada.",
        link: "https://getsol.us/",
        imagem: "distro_icons/128/128_solus.png",
        dataLancamento: "2015",
        requisitos: "2 GB RAM, 20 GB de espaço em disco",
        foco: "desktop",
        gerenciadorPacotes: "eopkg",
        ambienteDesktopPadrao: "Budgie",
        pros: "Experiência de usuário coesa, ambiente desktop moderno, fácil de usar",
        contras: "Menos suporte a software de terceiros em comparação com outras distros"
    },
    {
        titulo: "Elementary OS",
        descricao: "O Elementary OS é conhecido por seu design minimalista e foco em simplicidade e beleza. Baseado no Ubuntu, ele oferece uma experiência intuitiva com uma interface gráfica elegante chamada Pantheon. O Elementary OS é ideal para usuários que valorizam um ambiente de desktop limpo e bem projetado. Embora ofereça uma boa base, a quantidade de software disponível pode ser mais limitada em comparação com outras distribuições.",
        link: "https://elementary.io/",
        imagem: "distro_icons/128/128_elementary.png",
        dataLancamento: "2011",
        requisitos: "1 GB RAM, 15 GB de espaço em disco",
        foco: "desktop",
        gerenciadorPacotes: "apt",
        ambienteDesktopPadrao: "Pantheon",
        pros: "Design minimalista e elegante, interface intuitiva, fácil de usar",
        contras: "Menos software disponível, algumas limitações na personalização"
    },
    {
        titulo: "Deepin",
        descricao: "O Deepin é uma distribuição que se destaca por sua interface de usuário altamente visual e amigável. Desenvolvido na China, o Deepin oferece uma experiência moderna e fluida com o ambiente desktop Deepin DE. É ideal para quem busca uma distribuição com um design bonito e um foco na facilidade de uso. Embora seja atraente para novos usuários, a base de usuários fora da China pode ser menor, e o suporte a algumas aplicações pode ser limitado.",
        link: "https://www.deepin.org/",
        imagem: "distro_icons/128/128_deepin.png",
        dataLancamento: "2004",
        requisitos: "2 GB RAM, 20 GB de espaço em disco",
        foco: "desktop",
        gerenciadorPacotes: "dpkg",
        ambienteDesktopPadrao: "Deepin DE",
        pros: "Interface moderna e atraente, fácil de usar, experiência fluida",
        contras: "Menos suporte fora da China, base de usuários menor"
    },
    {
        titulo: "Zorin OS",
        descricao: "O Zorin OS é uma distribuição baseada no Ubuntu, projetada para oferecer uma experiência semelhante ao Windows, facilitando a transição para novos usuários que vêm do sistema da Microsoft. Com uma interface intuitiva e uma variedade de ferramentas para ajudar na migração, o Zorin OS é ideal para iniciantes. Ele também oferece versões gratuitas e pagas, com a versão paga oferecendo recursos adicionais e suporte premium.",
        link: "https://zorin.com/os/",
        imagem: "distro_icons/128/128_zorin.png",
        dataLancamento: "2008",
        requisitos: "2 GB RAM, 15 GB de espaço em disco",
        foco: "desktop",
        gerenciadorPacotes: "apt",
        ambienteDesktopPadrao: "Zorin Appearance",
        pros: "Facilita a transição do Windows, interface intuitiva, boa documentação",
        contras: "Versão paga necessária para recursos avançados, menos conhecida fora do mercado de iniciantes"
    },
    {
        titulo: "Gentoo",
        descricao: "O Gentoo é uma distribuição que oferece um alto nível de personalização e controle sobre o sistema. É conhecida por sua abordagem 'source-based', onde os pacotes são compilados a partir do código fonte, permitindo uma otimização profunda do sistema. É ideal para usuários avançados que desejam construir um sistema sob medida. No entanto, a instalação e a manutenção podem ser desafiadoras para iniciantes devido ao seu nível de complexidade.",
        link: "https://www.gentoo.org/",
        imagem: "distro_icons/128/128_gentoo.png",
        dataLancamento: "2002",
        requisitos: "512 MB RAM, 10 GB de espaço em disco",
        foco: "personalização, desenvolvimento",
        gerenciadorPacotes: "Portage",
        ambienteDesktopPadrao: "Nenhum (usuário escolhe)",
        pros: "Altamente personalizável, controle total sobre o sistema, otimização profunda",
        contras: "Instalação e manutenção complexas, não ideal para iniciantes"
    },
    {
        titulo: "Slackware",
        descricao: "Slackware é uma das distribuições mais antigas e respeitadas, conhecida por sua simplicidade e aderência aos princípios Unix. É uma distribuição altamente configurável e permite aos usuários aprender sobre o funcionamento interno do sistema operacional. Slackware é ideal para usuários avançados que preferem um sistema sem muitas modificações ou adições de pacotes pré-configurados. No entanto, a falta de algumas facilidades de configuração pode ser um desafio para iniciantes.",
        link: "https://www.slackware.com/",
        imagem: "distro_icons/128/128_slackware.png",
        dataLancamento: "1993",
        requisitos: "64 MB RAM, 4 GB de espaço em disco",
        foco: "personalização, servidores",
        gerenciadorPacotes: "Slackware pkgtools",
        ambienteDesktopPadrao: "Nenhum (usuário escolhe)",
        pros: "Simplicidade, controle total, adesão aos princípios Unix",
        contras: "Curva de aprendizado íngreme, menos suporte a software moderno"
    },
    {
        titulo: "Puppy Linux",
        descricao: "O Puppy Linux é uma distribuição leve e rápida projetada para rodar em hardware mais antigo ou com poucos recursos. É conhecida por seu tamanho pequeno e por oferecer uma experiência completa de desktop mesmo em sistemas com recursos limitados. O Puppy Linux é ideal para recuperação de sistemas e para usuários que precisam de uma distribuição eficiente para máquinas mais antigas. No entanto, sua interface e funcionalidades podem não ser tão modernas quanto outras distribuições.",
        link: "http://puppylinux.com/",
        imagem: "distro_icons/128/128_puppy_brown.png",
        dataLancamento: "2003",
        requisitos: "256 MB RAM, 1 GB de espaço em disco",
        foco: "desktop leve, recuperação",
        gerenciadorPacotes: "Puppy Package Manager",
        ambienteDesktopPadrao: "JWM/Rox",
        pros: "Leve e rápido, ideal para hardware antigo",
        contras: "Interface menos moderna, menos suporte a software"
    },
    {
        titulo: "EndeavourOS",
        descricao: "EndeavourOS é uma distribuição baseada no Arch Linux que oferece uma instalação mais amigável e uma configuração mais simples do que o Arch Linux puro. Com um instalador gráfico e uma configuração inicial mais fácil, o EndeavourOS é ideal para usuários que desejam a experiência do Arch sem a complexidade de uma instalação manual. A distribuição é conhecida por sua comunidade ativa e pelo suporte a várias opções de ambientes de desktop.",
        link: "https://endeavouros.com/",
        imagem: "distro_icons/128/128_endeavour.png",
        dataLancamento: "2019",
        requisitos: "512 MB RAM, 10 GB de espaço em disco",
        foco: "desktop, iniciantes em Arch",
        gerenciadorPacotes: "pacman",
        ambienteDesktopPadrao: "XFCE",
        pros: "Instalação mais fácil que o Arch, comunidade ativa",
        contras: "Ainda relativamente novo, pode ter menos suporte para alguns pacotes"
    },
    {
        titulo: "Clear Linux",
        descricao: "Desenvolvido pela Intel, o Clear Linux é uma distribuição otimizada para desempenho em hardware Intel, mas pode ser usado em outras plataformas também. É conhecida por seu foco em segurança, desempenho e atualizações contínuas. O Clear Linux é ideal para quem busca uma distribuição com ótimo desempenho em hardware recente e otimizações específicas para aplicações intensivas em recursos.",
        link: "https://clearlinux.org/",
        imagem: "distro_icons/128/128_clear.png",
        dataLancamento: "2015",
        requisitos: "2 GB RAM, 20 GB de espaço em disco",
        foco: "desempenho, segurança",
        gerenciadorPacotes: "swupd",
        ambienteDesktopPadrao: "GNOME",
        pros: "Ótimo desempenho, atualizações contínuas, otimizações para hardware Intel",
        contras: "Menos suporte para hardware não Intel, menos opções de personalização"
    },
    {
        titulo: "NixOS",
        descricao: "NixOS é uma distribuição Linux inovadora que utiliza o gerenciador de pacotes Nix para garantir uma instalação e atualização confiáveis. Cada pacote é isolado, o que permite uma configuração e manutenção do sistema mais seguras e previsíveis. É ideal para usuários que desejam uma configuração de sistema totalmente reprodutível e uma abordagem diferente à gestão de pacotes e configurações.",
        link: "https://nixos.org/",
        imagem: "distro_icons/128/128_nixos.png",
        dataLancamento: "2003",
        requisitos: "1 GB RAM, 10 GB de espaço em disco",
        foco: "gestão de pacotes, reprodutibilidade",
        gerenciadorPacotes: "Nix",
        ambienteDesktopPadrao: "GNOME",
        pros: "Gerenciamento de pacotes inovador, configuração reprodutível",
        contras: "Curva de aprendizado, menos suporte para pacotes de terceiros"
    },
    // {
    //     titulo: "LXLE",
    //     descricao: "LXLE é uma distribuição baseada no Ubuntu com o ambiente desktop LXDE, projetada para ser leve e rápida. Ideal para hardware mais antigo, o LXLE oferece uma interface gráfica simples e um desempenho eficiente. É uma boa opção para usuários que desejam uma distribuição que seja fácil de usar e que funcione bem em computadores com especificações mais baixas.",
    //     link: "http://lxle.net/",
    //     imagem: "distro_icons/128/128_lxle.png",
    //     dataLancamento: "2014",
    //     requisitos: "512 MB RAM, 5 GB de espaço em disco",
    //     foco: "desktop leve",
    //     gerenciadorPacotes: "apt",
    //     ambienteDesktopPadrao: "LXDE",
    //     pros: "Leve e rápido, ideal para hardware antigo",
    //     contras: "Interface simples, menos recursos avançados"
    // },
    {
        titulo: "AntiX",
        descricao: "AntiX é uma distribuição baseada no Debian projetada para ser leve e eficiente, com um foco em fornecer uma alternativa aos sistemas mais pesados. Utiliza o ambiente desktop IceWM ou Fluxbox, ambos conhecidos por sua leveza. O AntiX é ideal para sistemas mais antigos e para usuários que buscam um sistema operacional rápido e eficiente sem comprometer a funcionalidade.",
        link: "https://antixlinux.com/",
        imagem: "distro_icons/128/128_antix.png",
        dataLancamento: "2008",
        requisitos: "256 MB RAM, 2 GB de espaço em disco",
        foco: "desktop leve",
        gerenciadorPacotes: "apt",
        ambienteDesktopPadrao: "IceWM/Fluxbox",
        pros: "Muito leve e rápido, ideal para hardware antigo",
        contras: "Menos recursos gráficos avançados, pode exigir mais configuração manual"
    },
    {
        titulo: "Bodhi Linux",
        descricao: "Bodhi Linux é uma distribuição baseada no Ubuntu que se destaca por seu ambiente desktop minimalista e altamente configurável, chamado Enlightenment. É ideal para usuários que gostam de um sistema limpo e personalizável, com uma abordagem que permite ao usuário construir seu ambiente de desktop de acordo com suas preferências. Bodhi é leve e adequado para computadores mais antigos.",
        link: "https://www.bodhilinux.com/",
        imagem: "distro_icons/128/128_bodhi.png",
        dataLancamento: "2011",
        requisitos: "512 MB RAM, 5 GB de espaço em disco",
        foco: "desktop leve, personalização",
        gerenciadorPacotes: "apt",
        ambienteDesktopPadrao: "Enlightenment",
        pros: "Ambiente desktop minimalista e configurável, leve e rápido",
        contras: "Menos suporte a software de terceiros, pode exigir configuração adicional"
    },
    // {
    //     titulo: "Calculate Linux",
    //     descricao: "Calculate Linux é uma distribuição baseada no Gentoo projetada para oferecer uma instalação rápida e configuração fácil com uma interface amigável. É conhecida por seu foco em proporcionar uma experiência robusta e personalizável com a flexibilidade do Gentoo. Calculate Linux é ideal para usuários que desejam os benefícios do Gentoo com um processo de instalação mais amigável.",
    //     link: "https://calculate-linux.org/",
    //     imagem: "distro_icons/128/128_calculate.png",
    //     dataLancamento: "2007",
    //     requisitos: "1 GB RAM, 10 GB de espaço em disco",
    //     foco: "desktop, servidores",
    //     gerenciadorPacotes: "Portage",
    //     ambienteDesktopPadrao: "KDE Plasma",
    //     pros: "Instalação mais fácil que o Gentoo, altamente configurável",
    //     contras: "Menos conhecida, pode ter menos suporte para pacotes recentes"
    // },
    // {
    //     titulo: "MakuluLinux",
    //     descricao: "MakuluLinux é uma distribuição que visa proporcionar uma experiência de desktop altamente personalizável e eficiente. Com base no Debian, o MakuluLinux oferece várias edições com diferentes ambientes de desktop, permitindo aos usuários escolherem a interface que melhor se adapta às suas necessidades. É uma boa opção para quem deseja uma distribuição estável com flexibilidade de personalização.",
    //     link: "https://www.makululinux.com/",
    //     imagem: "distro_icons/128/128_makulu.png",
    //     dataLancamento: "2011",
    //     requisitos: "2 GB RAM, 15 GB de espaço em disco",
    //     foco: "desktop, personalização",
    //     gerenciadorPacotes: "apt",
    //     ambienteDesktopPadrao: "Vários (dependendo da edição)",
    //     pros: "Diversas opções de ambiente desktop, altamente personalizável",
    //     contras: "Menos conhecida, algumas edições podem não ter suporte contínuo"
    // }
];